#!/usr/bin/env python3
"""
pixel/ の 90枚の .json グリッドを、アプリ用の 1 ファイル
app/src/creatureData.ts に集約する。

各 (key, state) は 3 コマ共通パレットなので、パレット + 各コマを
「1セル=1文字」の文字列(透明は '.')にエンコードして軽量化する。
"""
import os
import re
import json
import glob

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PIXEL = os.path.join(ROOT, 'pixel')
OUT_TS = os.path.abspath(os.path.join(ROOT, '..', 'app', 'src', 'creatureData.ts'))

# インデックス→文字(パレット参照用)。透明は '.'
CHARS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'
NAME_RE = re.compile(r'^(?P<key>.+)_(?P<state>egg|baby|adult)_(?P<frame>\d+)$')


def main():
    # data[key][state] = {'palette': [...], 'frames': {frame: [rowstr,...]}}
    data = {}
    size = None
    for f in sorted(glob.glob(os.path.join(PIXEL, '*.json'))):
        stem = os.path.splitext(os.path.basename(f))[0]
        m = NAME_RE.match(stem)
        if not m:
            continue
        key, state, frame = m.group('key'), m.group('state'), int(m.group('frame'))
        grid = json.load(open(f))['grid']
        size = len(grid)
        data.setdefault(key, {}).setdefault(state, {})[frame] = grid

    creatures = {}
    for key, states in data.items():
        creatures[key] = {}
        for state, frames in states.items():
            # 3コマ通しのパレットを作る
            palette, idx = [], {}
            for fr in sorted(frames):
                for row in frames[fr]:
                    for c in row:
                        if c is not None and c not in idx:
                            idx[c] = len(palette)
                            palette.append(c)
            if len(palette) > len(CHARS):
                raise SystemExit(f'palette too big: {key}/{state} {len(palette)}')
            enc = []
            for fr in sorted(frames):
                rows = [''.join('.' if c is None else CHARS[idx[c]] for c in row) for row in frames[fr]]
                enc.append(rows)
            creatures[key][state] = {'palette': palette, 'frames': enc}

    lines = [
        '// AUTO-GENERATED by avatars/tools/export_data.py — 手で編集しない',
        f'export const PIXEL_SIZE = {size};',
        "export const CHARS = '" + CHARS + "';",
        'export type StageData = { palette: string[]; frames: string[][] };',
        'export type CreatureData = { egg: StageData; baby: StageData; adult: StageData };',
        'export const CREATURE_DATA: Record<string, CreatureData> = ' +
        json.dumps(creatures, ensure_ascii=False, separators=(',', ':')) + ';',
        '',
    ]
    os.makedirs(os.path.dirname(OUT_TS), exist_ok=True)
    with open(OUT_TS, 'w') as f:
        f.write('\n'.join(lines))
    kb = os.path.getsize(OUT_TS) / 1024
    print(f'書き出し: {OUT_TS} ({kb:.0f} KB, {len(creatures)}種)')


if __name__ == '__main__':
    main()
